autoDiscovery:
    clusterName: {{cluster_name}}
awsRegion: {{region_name}}
image:
    tag: v1.28.5
nodeSelector:
    app: spark    
podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
extraArgs:
    skip-nodes-with-system-pods: false
    scale-down-unneeded-time: 5m
    scale-down-unready-time: 10m
rbac:
    serviceAccount:
        create: false
        name: cluster-autoscaler

  