autoDiscovery:
    clusterName: {{cluster_name}}
awsRegion: {{region_name}}
image:
    tag: v1.26.6
nodeSelector:
    app: spark    
podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
extraArgs:
    skip-nodes-with-system-pods: false
    scale-down-unneeded-time: 30s
    scale-down-unready-time: 1m
    expander: least-waste
rbac:
    serviceAccount:
        create: false
        name: cluster-autoscaler

  