kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{MY_SA}}-role-binding
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: {{MY_SA}}
    namespace: spark
roleRef:
  kind: Role
  name: etl-workflow-role
  apiGroup: rbac.authorization.k8s.io